//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATRACTool_Reloaded.Localizable {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XAMLWindowLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XAMLWindowLocalization() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATRACTool_Reloaded.Localizable.XAMLWindowLocalization", typeof(XAMLWindowLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuccessCaption {
            get {
                return ResourceManager.GetString("SuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC9] 12000Hz (12000Hz, 48000Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target12kHzCaption {
            get {
                return ResourceManager.GetString("Target12kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC9] 16000Hz (48000Hz Only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target16kHzCaption {
            get {
                return ResourceManager.GetString("Target16kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC9] 24000Hz (24000Hz, 48000Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target24kHzCaption {
            get {
                return ResourceManager.GetString("Target24kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC9] 32000Hz (48000Hz Only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target32kHzCaption {
            get {
                return ResourceManager.GetString("Target32kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC3+ / ATRAC9] 44100Hz (ATRAC3+ is best for PSP) (ATRAC9 is 48000Hz Only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target44kHzCaption {
            get {
                return ResourceManager.GetString("Target44kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC3+ / ATRAC9] 48000Hz (ATRAC3+ is best for PS3) (ATRAC9 is 48000Hz Only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target48kHzCaption {
            get {
                return ResourceManager.GetString("Target48kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [For ATRAC9] 8000Hz (48000Hz Only) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Target8kHzCaption {
            get {
                return ResourceManager.GetString("Target8kHzCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarningCaption {
            get {
                return ResourceManager.GetString("WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowATWSelect_Format {
            get {
                return ResourceManager.GetString("WindowATWSelect_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the destination format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowATWSelect_Title {
            get {
                return ResourceManager.GetString("WindowATWSelect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output method: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowATWSelectTarget_OutputMethod {
            get {
                return ResourceManager.GetString("WindowATWSelectTarget_OutputMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify output method for WAVE files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowATWSelectTarget_Title {
            get {
                return ResourceManager.GetString("WindowATWSelectTarget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   portable (Small capacity, .NET runtime installation required) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowUpdateApplicationType_Combobox_Portable {
            get {
                return ResourceManager.GetString("WindowUpdateApplicationType_Combobox_Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   release (High capacity, no .NET runtime installation required) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowUpdateApplicationType_Combobox_Release {
            get {
                return ResourceManager.GetString("WindowUpdateApplicationType_Combobox_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Application Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowUpdateApplicationType_Title {
            get {
                return ResourceManager.GetString("WindowUpdateApplicationType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Type: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowUpdateApplicationType_Type {
            get {
                return ResourceManager.GetString("WindowUpdateApplicationType_Type", resourceCulture);
            }
        }
    }
}
